server.port: 8002
spring.cloud.stream:
  poller.maxMessagesPerPoll: 100
  function.definition: loadPlant;loadCompany;loadSalesOrganisation
  bindings:
    loadCompany-out-0:
      destination: Company
    loadPlant-out-0:
      destination: Plant
    loadSalesOrganisation-out-0:
      destination: SalesOrganisation
  kafka:
    streams:
      binder:
        applicationId: Fin2Configuration_Organisation
        configuration:
          commit.interval.ms: 100
          default:
            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#Enable metrics
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: metrics,health
#Enable logging to debug for spring kafka config
logging:
  level:
    org.springframework.kafka.config: debug
