server.port: 8085
spring.cloud.function.definition: processSalesOrganisation;processPlant;processCompany
spring.cloud.stream:
  kafka.streams.bindings:
    processSalesOrganisation_in.applicationId: Fin2ConfigurationOrganisation_SalesOrganistation
    processCompany_in.applicationId: Fin2ConfigurationOrganisation_Company
    processPlant_in.applicationId: Fin2ConfigurationOrganisation_Plant
  bindings:
    processSalesOrganisation-in-0:
      destination: input_org
    processSalesOrganisation-out-0:
      destination: SalesOrganisation
    processCompany-in-0:
      destination: input_company
    processCompany-out-0:
      destination: Company
    processPlant-in-0:
      destination: input_plant
    processPlantSalesOrganisation-out-0:
      destination: Plant
  kafka:
    streams:
      binder:
        configuration:
          commit.interval.ms: 100
          default:
            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#Enable metrics
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: metrics,health
#Enable logging to debug for spring kafka config
logging:
  level:
    org.springframework.kafka.config: debug
