server.port: 8086
spring.cloud.function.definition: processBusinessPartner;processCostCenter;processMaterial
spring.cloud.stream:
  kafka.streams.bindings:
    processBusinessPartner_in.applicationId: Fin2Masterdata_BusinessPartner
    processCostCenter_in.applicationId: Fin2Masterdata_CostCenter
    processMaterial_in.applicationId: Fin2Masterdata_Material
  bindings:
    processBusinessPartner-in-0:
      destination: input_bp
    processBusinessPartner-out-0:
      destination: BusinessPartner
    processCostCenter-in-0:
      destination: input_cc
    processCostCenter-out-0:
      destination: CostCenter
    processMaterial-in-0:
      destination: input_mat
    processMaterial-out-0:
      destination: Material
  kafka:
    streams:
      binder:
        configuration:
          commit.interval.ms: 100
          default:
            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
            value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#Enable metrics
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: metrics,health
#Enable logging to debug for spring kafka config
logging:
  level:
    org.springframework.kafka.config: debug
